### ISSUE TITLE
Refactor the codebase so that I can generate automatically the raw figure for the paper

### ISSUE THREAD

**Issue by yacineMahdid** [BIAPT/Assessing-the-Quality-of-Wearable-EEG-Systems-Using-Functional-Connectivity#4]
By raw, I meant not polished but in a good shape to be cut and paste into inkscape (the software I am using to edit pictures). Here I should replicate what I had before.

**Comment by yacineMahdid** [comment]
Good news I already have the spatially downsampled data for all the headset. This can be used directly to generate all the figure in one go.

**Comment by yacineMahdid** [comment]
# TODO
- [x] Modify NeuroAlgo Recording class to be able to load a .mat file as well as a .set file
- [x] Setup the analysis pipeline to have the same parameters as we are using in the paper
- [x] Run the full analysis remotely on the lab computer on all frequency bands

At this point I realised that I have to reorder all the headset, however I only made my reordering function work for the egi129. Will need to create a cassette for the other headset too otherwise this is going to be a mess. They are not ordered in a `FTCPO` order by default.
- [x] Setup the figure generation code to churn through the `/result` folder
- [x] Reproduce all the figures in the paper at the frequency band at alpha ( + full band for spectrogram) 
- [x] create the `.csv` with the `FTCPO` ordering for all headsets.
- [x] test the reordering with all the headsets.
- [x] make a module to only take the left or right part of the brain
- [x] figure out a way to scale automatically by groups of four in the figures of all headsets or 2 in the egi full figure.

At this point I can automatically create the figures, I just need to automate it for wPLI and dPLI together without making the code a big mess and generating `.png` file that are exactly of the right size.
- [x] figure out how to scale the figure to be of the approximate size we need to cut it and paste it in inkscape.
- [x] figure out how to save the `.png` version of the figure instead of the `.fig`
- [x] create the wPLI and dPLI figures at all frequency bands for all headset (including the downsampled version)
- [ ] figure out wtf should I do with 108 plots?

At this point the pipeline should be documented well enough so that I can apply it to generate the analysis for all the other frequency bands.
